# Generated by Django 5.0.4 on 2024-05-20 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(related_name='working_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
