# Generated by Django 5.0.4 on 2024-05-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Direktor'), (2, 'Nazoratchi'), (3, 'Hodim'), (4, "Bo'lim boshlig'i"), (5, 'Mehmon')], default=3, null=True),
        ),
    ]
