# Generated by Django 5.0.4 on 2024-05-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='manager',
        ),
    ]
