# Generated by Django 5.0.4 on 2024-05-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_submission_ball_remove_submission_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
