# Generated by Django 5.0.4 on 2024-04-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notefication'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefication',
            name='unread',
            field=models.BooleanField(default=False),
        ),
    ]
