# Generated by Django 5.0.4 on 2024-05-21 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mark', to='dashboard.submission'),
        ),
    ]
