# Generated by Django 5.0.4 on 2024-04-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_notefication_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notefication',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
