# Generated by Django 5.0.4 on 2024-04-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_result_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefication',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, "Rag'batlantirish"), (2, "Ma'lumot berish"), (3, 'Tanqid qilish'), (4, 'Ogohlantirish')], default=1),
        ),
    ]
