# Generated by Django 5.0.4 on 2024-05-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_submission_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
